name: Deploy to Google Cloud Platform

on:
  push:
    branches:
      - main  # Sesuaikan dengan branch yang kamu gunakan

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17'

      - name: Install dependencies
        run: |
          npm install
          npm install --save-dev supertest
          npm install --save-dev jest
          
      - name: SSH into Google Cloud VM and deploy
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          # Set up GCP CLI
          echo "$GCP_SA_KEY" | base64 --decode > /tmp/gcp-key.json
          gcloud auth activate-service-account --key-file /tmp/gcp-key.json
          gcloud config set project your-gcp-project-id  # Ganti dengan ID proyek GCP kamu
          
          # Upload ke server GCP
          scp -i /tmp/gcp-key.json -o StrictHostKeyChecking=no -r ./ user@your-gcp-ip:/path/to/your/app

      - name: Install Node.js and PM2 on GCP VM
        run: |
          ssh -i /tmp/gcp-key.json user@your-gcp-ip << 'EOF'
            sudo apt update
            sudo apt install nodejs npm -y
            npx prisma migrate dev --name init
            sudo npm install -g pm2
            sudo npm install -g jest
            cd 24001200-km7-OKK-Aplikasi-Galeri-Seni
            pm2 start app.js --name "art-gallery-app"
            pm2 save
          EOF

      - name: Clean up
        run: |
          rm /tmp/gcp-key.json
