name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}

      - name: Copy files to GCP
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" \
          --exclude '.github/' \
          --exclude 'node_modules/' \
          ./ ${{ secrets.GCP_SSH_USER }}@${{ secrets.GCP_HOST }}:/home/${{ secrets.GCP_SSH_USER }}/24001200-km7-OKK-Aplikasi-Galeri-Seni

      - name: Deploy application on GCP
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_SSH_USER }}@${{ secrets.GCP_HOST }} << 'EOF'
            cd /home/${{ secrets.GCP_SSH_USER }}/24001200-km7-OKK-Aplikasi-Galeri-Seni/ch6

            # Create .env file with GitHub secrets
            cat <<EOT > .env
            IMAGEKIT_PUBLIC_KEY=${{ secrets.IMAGEKIT_PUBLIC_KEY }}
            IMAGEKIT_PRIVATE_KEY=${{ secrets.IMAGEKIT_PRIVATE_KEY }}
            IMAGEKIT_URL_ENDPOINT=${{ secrets.IMAGEKIT_URL_ENDPOINT }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            EOT

            sudo apt update
            sudo apt-get install -y curl
            curl -fsSL https://deb.nodesource.com/setup_20.x -o nodesource_setup.sh
            sudo -E bash nodesource_setup.sh
            sudo apt-get install -y nodejs
            npm install
            npx prisma migrate dev --name init
            npx prisma migrate deploy
            sudo npm install -g pm2 jest
            pm2 stop art-gallery-app || true
            pm2 start app.js --name "art-gallery-app"
            pm2 save
          EOF
